# Generated by Django 3.2.20 on 2023-08-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
