# Generated by Django 3.2.20 on 2023-08-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='lecturer_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
