# Generated by Django 3.2.20 on 2023-08-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_semester_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
