# Generated by Django 3.2.20 on 2023-08-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_lecturer_lecturer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
