# Generated by Django 3.2.20 on 2023-08-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='id',
            field=models.IntegerField(unique=True),
        ),
    ]
