# Generated by Django 3.2.20 on 2023-08-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_student_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='organized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.lecturer'),
        ),
    ]
