# Generated by Django 3.2.20 on 2023-08-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_semester_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='module_code4',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='module_code5',
        ),
    ]
