# Generated by Django 3.2.20 on 2023-08-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_lecturer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='id',
            new_name='lecturer_id',
        ),
    ]
