# Generated by Django 3.2.20 on 2023-08-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_organized_by_module_lecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='Lecture',
            new_name='lecturer',
        ),
    ]
