# Generated by Django 3.2.20 on 2023-08-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_id_lecturer_lecturer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='lecturer_id',
            new_name='id',
        ),
    ]
