# Generated by Django 3.2.20 on 2023-08-06 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='module_code1',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='Form_Module1', to='application.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='module_code2',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='Form_Module2', to='application.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='module_code3',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='Form_Module3', to='application.module'),
            preserve_default=False,
        ),
    ]
