# Generated by Django 3.2.20 on 2023-08-06 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20230806_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='faculty',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
