# Generated by Django 3.2.20 on 2023-08-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_semester_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Form_Module1', to='application.module')),
                ('module_code2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Form_Module2', to='application.module')),
                ('module_code3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Form_Module3', to='application.module')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.student')),
            ],
        ),
    ]
