# Generated by Django 3.2.20 on 2023-08-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20230804_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
